#-------------------------------------------------------------------------------
# GraphBLAS/MATLAB/Makefile
#-------------------------------------------------------------------------------

# SuiteSparse:GraphBLAS, Timothy A. Davis, (c) 2017-2018, All Rights Reserved.
# http://suitesparse.com   See GraphBLAS/Doc/License.txt for license.

#-------------------------------------------------------------------------------

clean:
	- $(RM) -rf *.o *.mex*

purge: clean

distclean: clean

